name: square equation test

on:
  push:
    branches: ["xUnix"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore SquareEquationLib

      - name: Build
        run: dotnet build SquareEquationLib --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test
        run: ./SquareEquationTest ./SquareEquationLib/bin/Debug/net7.0/SquareEquationLib.dll
      - name: Build2
        run: dotnet build SquareEquation.Tests

      - name: Testing
        run: dotnet test SquareEquation.Tests --collect:"XPlat Code Coverage"
      - name: Coverage
        uses: codecov/codecov-action@v1.2.0
        with:
          files: /home/ubuntu/OmSTU/SquareEquation.Tests/TestResults/969e0e5d-d487-41d0-8487-5f8f07696d5b/coverage.cobertura.xml
          name: codecov-umbrella
          fail_ci_if_error: true
